### ISSUE TITLE
Ticking Entity Crash

### ISSUE THREAD

**Issue by Karashok-Leo** [cleannrooster/Spellblade-Next#20] opened 2024-02-08 03:25 UTC
[crash-2024-02-08_11.15.21-server.txt](https://github.com/cleannrooster/Spellblade-Next/files/14203892/crash-2024-02-08_11.15.21-server.txt)

**Comment by cleannrooster** [comment] 2024-02-08 04:06
Hi, this is likely an issue with the Conjuring mod, I see no issue with the way I have it implemented.

In the LivingEntityMixin.java I see in the Conjuring mod repo, I see a case of LivingEntity cast to PlayerEntity unchecked, so this is likely the the cause of the issue that can be fixed on the end of the author of the Conjuring mod. 

Here it is: https://github.com/wisp-forest/conjuring/blob/bdc3d1e49dbccbc9e970984824ea621c691bdb14/src/main/java/com/glisco/conjuring/mixin/LivingEntityMixin.java#L82

**Closed as completed by cleannrooster** 2024-02-08 04:06 UTC

**Comment by gliscowo** [comment] 2024-02-17 16:43
Hey, author of Conjuring Conjuring here. While I do agree that Conjuring's implementation of this check is probably not optimal, I'm rather confused as to how your mod would be triggering this crash. The only way I can see for that to happen is by causing damage using the `PLAYER_ATTACK` damage type... but without an actual player attacking? That seems wrong to me and like it would cause issues with other mods too.

Since I can't seem to find the implementation of the class causing the crash in this repo, could you maybe elaborate a bit further on why you believe that your code is not responsible as well?

Cheers

**Comment by cleannrooster** [comment] 2024-03-03 17:24
Hi, I'm not sure how my code is allowing something that isn't a player
attack to pass a player attack damage type check, I'll tell you if i figure
it out.
